stages:
  - build-assets
  - build-page
  - deploy

build-assets:
  # Needed vars for asset generation: NPM_FA_TOKEN
  stage: build-assets
  image: node:12.13.1
  only:
    - master
  artifacts:
    paths:
      - assets/dist
  before_script:
    - echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
    - echo "//npm.fontawesome.com/:_authToken=$NPM_FA_TOKEN" >> .npmrc
  script:
    - npm install
    - npm run production

build-page:
  stage: build-page
  image: monachus/hugo
  only:
    - master
  dependencies:
    - build-assets
  artifacts:
    paths:
      - public
  script:
    - hugo

deploy:
  # Needed vars for deployment: DEPLOY_HOST, DEPLOY_PATH, DEPLOY_PRIVATE_KEY
  stage: deploy
  image: alpine:latest
  only:
    - master
  before_script:
    # Setup SSH
    - apk update
    - apk add openssh-client
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | ssh-add -
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    # Deploy the page to the server
    - export DEPLOY_TS=$(date +%Y-%m-%d_%H-%M-%S)
    - export DEPLOY_DEST=$DEPLOY_PATH/releases/$DEPLOY_TS
    - tar -czf /tmp/build.tar.gz public
    - ssh $DEPLOY_HOST "mkdir -p $DEPLOY_DEST"
    - scp /tmp/build.tar.gz $DEPLOY_HOST:$DEPLOY_DEST
    - ssh $DEPLOY_HOST "cd $DEPLOY_DEST && tar -xzf build.tar.gz"
    - ssh $DEPLOY_HOST "rm -f $DEPLOY_PATH/current && ln -s $DEPLOY_DEST $DEPLOY_PATH/current"
