title = "Kovah.de Blog"
baseURL = "https://blog.kovah.de/"
assetDir = "./assets/dist"
paginate = 5
relativeURLs = false

pygmentsCodeFences = false

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
  defaultAuthor = "Kevin Woblick"
  publisher = "Kevin Woblick"
  webmentionUrl = "https://blog.kovah.de"
  gumletUrl = "https://kvh-blog.gumlet.com"

[imaging]
quality = 85

[languages]
[languages.en]
  contentDir = "content/en"
  languageName = "EN"
  languageCode = "en-us"
  weight = 1

[languages.de]
  contentDir = "content/de"
  languageName = "DE"
  languageCode = "de-de"
  weight = 2

[[languages.en.menu.main]]
url    = "/categories/article"
name   = "Articles"
weight = 1

[[languages.en.menu.main]]
url    = "/categories/news"
name   = "News"
weight = 2

[[languages.en.menu.main]]
url    = "/categories/test"
name   = "Tests"
weight = 3

[[languages.en.menu.main]]
url    = "/categories/tutorial"
name   = "Tutorials"
weight = 4


[[languages.de.menu.main]]
url    = "/categories/artikel"
name   = "Artikel"
weight = 1

[[languages.de.menu.main]]
url    = "/categories/news"
name   = "News"
weight = 2

[[languages.de.menu.main]]
url    = "/categories/test"
name   = "Tests"
weight = 3

[[languages.de.menu.main]]
url    = "/categories/tutorial"
name   = "Tutorials"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"
